name: Deploy and Notify Discord

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit diff per file and send to Discord
        run: |
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          PREV_SHA=$(git rev-parse $COMMIT_SHA^ || echo "")
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          if [ -z "$PREV_SHA" ]; then
            echo "初回コミットのため差分なし"
            exit 0
          fi

          # 変更されたファイル一覧を取得
          FILES=$(git diff --name-only $PREV_SHA $COMMIT_SHA)

          for FILE in $FILES; do
            DIFF=$(git diff $PREV_SHA $COMMIT_SHA --color --patch --unified=3 -- "$FILE" | head -c 3500)
            DIFF_ESCAPED=$(echo "$DIFF" | sed 's/"/\\"/g')

            PAYLOAD=$(cat <<EOF
            {
              "embeds": [
                {
                  "title": "Commit: $COMMIT_MESSAGE",
                  "url": "$COMMIT_URL",
                  "color": 3066993,
                  "fields": [
                    {"name": "Author", "value": "$COMMIT_AUTHOR", "inline": true},
                    {"name": "File", "value": "$FILE", "inline": false},
                    {"name": "Diff", "value": "```diff\n$DIFF_ESCAPED\n```", "inline": false}
                  ]
                }
              ]
            }
            EOF
            )

            curl -H "Content-Type: application/json" \
                 -d "$PAYLOAD" \
                 ${{ secrets.DISCORD_WEBHOOK_URL }}
          done
