name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # デプロイしたいブランチ名（例: main, master）

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FLJP_API_KEY: ${{ secrets.FLJP_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

    

      - name: Inject API Key into v2/script.js
        run: |
          # 環境変数 FLJP_API_KEY を v2/script.js に反映
          sed -i "s|const API_KEY = '.*';|const API_KEY = '${FLJP_API_KEY}';|" v2/script.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # ルート直下を公開（index.htmlなど静的HTML）

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
