name: Deploy and Notify Discord

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  deploy-and-notify:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Check out repository
        uses: actions/checkout@v4

      # GitHub Pages 設定
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # アーティファクトをアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # ルート直下を公開（index.htmlなど静的HTML）

      # デプロイ
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      # Discord へコミット差分通知
      - name: Send commit diffs to Discord
        run: |
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          PREV_SHA=$(git rev-parse $COMMIT_SHA^ 2>/dev/null || echo "")
          if [ -z "$PREV_SHA" ]; then
            echo "初回コミットのため差分なし"
            exit 0
          fi

          FILES=$(git diff --name-only $PREV_SHA $COMMIT_SHA)
          if [ -z "$FILES" ]; then
            echo "差分ファイルなし"
            exit 0
          fi

          ALL_DIFF=""
          MAX_CHARS=3500

          for FILE in $FILES; do
            NUMSTAT=$(git diff $PREV_SHA $COMMIT_SHA --numstat -- "$FILE")
            ADDED=$(echo "$NUMSTAT" | awk '{print $1}')
            DELETED=$(echo "$NUMSTAT" | awk '{print $2}')

            # 差分取得して Markdown 用に ` をエスケープ
            FILE_DIFF=$(git diff $PREV_SHA $COMMIT_SHA --patch --unified=3 -- "$FILE" | sed 's/`/\\`/g')

            # 長さ制限
            if [ ${#FILE_DIFF} -gt $MAX_CHARS ]; then
              FILE_DIFF="${FILE_DIFF:0:$MAX_CHARS}\n... (diff truncated)"
            fi

            ALL_DIFF="$ALL_DIFF**$FILE** (+$ADDED/-$DELETED)\n$FILE_DIFF\n\n"
          done

          # Discord に送る JSON を jq で生成
          DISCORD_PAYLOAD=$(jq -n \
            --arg title "Commit: $COMMIT_MESSAGE" \
            --arg url "$COMMIT_URL" \
            --arg author "$COMMIT_AUTHOR" \
            --arg diff "$ALL_DIFF" \
            '{
              embeds: [
                {
                  title: $title,
                  url: $url,
                  color: 3066993,
                  fields: [
                    {name: "Author", value: $author, inline: true},
                    {name: "Changes", value: $diff, inline: false}
                  ]
                }
              ]
            }')

          # Discord に送信
          curl -s -H "Content-Type: application/json" -d "$DISCORD_PAYLOAD" ${{ secrets.DISCORD_WEBHOOK_URL }} || echo "Discord通知失敗"
