name: Deploy to GitHub Pages with Discord Notification

on:
  push:
    branches:
      - main # デプロイしたいブランチ

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリを取得
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. GitHub Pages 用にセットアップ
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. 公開するファイルをアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # ルート直下を公開 (index.htmlなど)

      # 4. デプロイ実行
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      # 5. Discord通知（モジュール不要）
      - name: Notify Discord
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 環境変数から情報を取得
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const branch = process.env.GITHUB_REF.replace('refs/heads/', '');
            const payload = JSON.parse(process.env.GITHUB_EVENT_PATH);
            const commitMessage = payload.head_commit?.message || "コミット情報なし";

            const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
            const url = `https://${repo}.github.io/`;

            const content = `✅ GitHub Pagesにデプロイ完了！\n` +
                            `**リポジトリ:** ${repo}\n` +
                            `**ブランチ:** ${branch}\n` +
                            `**最新コミット:** ${commitMessage}\n` +
                            `**公開URL:** <${url}>`;

            // fetch は github-script 内でグローバルに使用可能
            await fetch(webhookUrl, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ content })
            });
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
