name: Notify Discord on Commit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit diff
        run: |
          # コミット情報を取得
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          
          # 差分取得
          git clone --depth 2 https://github.com/${{ github.repository }} repo
          cd repo
          DIFF=$(git diff $COMMIT_SHA~1 $COMMIT_SHA --color)

          # 長すぎる場合は切り捨て
          DIFF="${DIFF:0:3500}"

          # JSON ペイロード作成
          PAYLOAD=$(jq -n \
            --argjson embeds "[{
              \"title\": \"New Commit\",
              \"url\": \"$COMMIT_URL\",
              \"color\": 3066993,
              \"fields\": [
                {\"name\": \"Author\", \"value\": \"$COMMIT_AUTHOR\", \"inline\": true},
                {\"name\": \"Message\", \"value\": \"$COMMIT_MESSAGE\", \"inline\": false},
                {\"name\": \"Diff\", \"value\": \"\`\`\`diff\n$DIFF\n\`\`\`\", \"inline\": false}
              ]
            }]" \
            '{embeds: $embeds}')
          
          curl -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
