name: Deploy and Notify Discord

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

    
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: . # ルート直下を公開（index.htmlなど静的HTML）

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true

      - name: Send commit diffs to Discord
        run: |
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          PREV_SHA=$(git rev-parse $COMMIT_SHA^ 2>/dev/null || echo "")
          if [ -z "$PREV_SHA" ]; then
            echo "初回コミットのため差分なし"
            exit 0
          fi

          FILES=$(git diff --name-only $PREV_SHA $COMMIT_SHA)
          if [ -z "$FILES" ]; then
            echo "差分ファイルなし"
            exit 0
          fi

          ALL_DIFF=""
          for FILE in $FILES; do
            DIFF=$(git diff $PREV_SHA $COMMIT_SHA --patch --unified=3 -- "$FILE" | head -c 3500)
            DIFF_ESCAPED=$(echo "$DIFF" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
            NUMSTAT=$(git diff $PREV_SHA $COMMIT_SHA --numstat -- "$FILE")
            ADDED=$(echo "$NUMSTAT" | awk '{print $1}')
            DELETED=$(echo "$NUMSTAT" | awk '{print $2}')
            ALL_DIFF="$ALL_DIFF**$FILE** (+$ADDED/-$DELETED)\n\`\`\`$DIFF_ESCAPED\`\`\`\n"
          done

          # Discord に送る JSON を別変数に格納
          DISCORD_PAYLOAD=$(jq -n \
            --arg title "Commit: $COMMIT_MESSAGE" \
            --arg url "$COMMIT_URL" \
            --arg author "$COMMIT_AUTHOR" \
            --arg diff "$ALL_DIFF" \
            '{
              embeds: [
                {
                  title: $title,
                  url: $url,
                  color: 3066993,
                  fields: [
                    {name: "Author", value: $author, inline: true},
                    {name: "Changes", value: $diff, inline: false}
                  ]
                }
              ]
            }')

          # Discord に送信
          curl -s -H "Content-Type: application/json" -d "$DISCORD_PAYLOAD" ${{ secrets.DISCORD_WEBHOOK_URL }} || echo "Discord通知失敗"
