name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # デプロイしたいブランチ名（例: main, master）

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit diffs to Discord
        run: |
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

          PREV_SHA=$(git rev-parse $COMMIT_SHA^ 2>/dev/null || echo "")
          if [ -z "$PREV_SHA" ]; then
            echo "初回コミットのため差分なし"
            exit 0
          fi

          FILES=$(git diff --name-only $PREV_SHA $COMMIT_SHA)
          if [ -z "$FILES" ]; then
            echo "差分ファイルなし"
            exit 0
          fi

          mkdir -p tmp
          echo "" > tmp/diff.txt

          for FILE in $FILES; do
            NUMSTAT=$(git diff $PREV_SHA $COMMIT_SHA --numstat -- "$FILE")
            ADDED=$(echo "$NUMSTAT" | awk '{print $1}')
            DELETED=$(echo "$NUMSTAT" | awk '{print $2}')

            FILE_DIFF=$(git diff $PREV_SHA $COMMIT_SHA --patch --unified=3 -- "$FILE" | head -c 3500 | sed 's/`/\\`/g')

            echo "**$FILE** (+$ADDED/-$DELETED)" >> tmp/diff.txt
            echo "$FILE_DIFF" >> tmp/diff.txt
            echo "" >> tmp/diff.txt
          done

          ALL_DIFF=$(cat tmp/diff.txt)

          DISCORD_PAYLOAD=$(jq -n \
            --arg title "Commit: $COMMIT_MESSAGE" \
            --arg url "$COMMIT_URL" \
            --arg author "$COMMIT_AUTHOR" \
            --arg diff "$ALL_DIFF" \
            '{
              embeds: [
                {
                  title: $title,
                  url: $url,
                  color: 3066993,
                  fields: [
                    {name: "Author", value: $author, inline: true},
                    {name: "Changes", value: $diff, inline: false}
                  ]
                }
              ]
            }'
          )

          curl -s -H "Content-Type: application/json" -d "$DISCORD_PAYLOAD" ${{ secrets.DISCORD_WEBHOOK_URL }} || echo "Discord通知失敗"
