# 修正されたワークフロー
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}  # シークレットからトークンを取得
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate config file
        run: |
          
          echo "window.env = { TOKEN: '$MY_TOKEN' };" > ./config.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          exclude: |
            node_modules/**
            .git/**
            .github/**

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                     \"username\": \"GitHub Actions\",
                     \"content\": \"📢 **Push detected!**\n\nリポジトリ: $GITHUB_REPOSITORY\nブランチ: $GITHUB_REF_NAME\nコミット: $GITHUB_SHA\nメッセージ: $(echo '${{ github.event.head_commit.message }}' | sed 's/\"/\\\"/g')\nユーザー: $GITHUB_ACTOR\"
                   }" \
               ${{ secrets.DISCORD_WEBHOOK }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
